### ISSUE TITLE
Error converting fig to gif

### ISSUE THREAD

**Issue by sikmir** [slazav/map_podm#6]
https://github.com/slazav/map_podm/blob/dd549329fa1d422658d810908b55047c222ecc9f/conf/pics/Makefile#L26-L27

I'm trying:
```sh
$ fig2dev -m7.5 -Lgif -t#ffffff avt.fig > avt.gif
Error when creating bitmap output
command was: { gs -q -dSAFER -r80 -g73x84 -sDEVICE=ppmraw -o - - | convert - -transparent#ffffff gif:-; } 2>/tmp/f2derrorbgWkBM
Messages resulting:
convert: unrecognized option `-transparent#ffffff' @ error/convert.c/ConvertImageCommand/3150.
```

Versions:
fig2dev 3.2.8a
ghostscript 9.53.3
imagemagick 7.0.11

**Comment by slazav** [comment]
Кажется, явная ошибка в fig2dev, забыт пробел. У меня все работает, потому что там пробуется несколько вариантов: netpbm, потом ImageMagick, потом GraphicsMagick. Если поставить netpbm, то будет работать через него.
Сейчас напишу людям из xfig...

**Comment by slazav** [comment]
https://sourceforge.net/p/mcj/tickets/121/

**Comment by sikmir** [comment]
Upstream ticket resolved, latest release fig2dev 3.2.8b contains the fix, it works properly now.
