### ISSUE TITLE
Но карте в районе ММБ 2024о нет имён СНТ

### ISSUE THREAD

**Issue by ioctl-user** [slazav/map_podm#8]
Вот фрагмент [карты с ММБ:](https://mmb.progressor.ru/mmbfiles/mmb2024o-whole.png):
![mmb](https://github.com/user-attachments/assets/beb74f44-59fe-498e-8130-174205298edf)

Вот снимок экрана телефона примерной этой же области с собранными плитками:
![tiles](https://github.com/user-attachments/assets/7ada132b-0a04-4690-a03a-af6682e1bbdc)

На картах ММБ есть имена СНТ, но их нет на собранных картах. И в исходниках карт тоже не видно.

Это поправимо?

**Comment by slazav** [comment]
Да, я когда-то пытался урезать лишние названия и объекты, приводить карту к некому общему стилю и масштабу. (это ведь какого-то старого ММБ район?) Потом почти забросил это дело, в результате этой картой толком не занимаюсь, она превращается постепенно в плохой OSM. Вряд ли можно исправить.

**Comment by ioctl-user** [comment]
Да, некогда ММБ там уже был.
До последнего обновления этой осенью этих названий тоже не было.
